# Target environment to update mbtiles

parameters:
- name: targetEnv
  displayName: Target environment
  type: string
  values:
    - production
    - staging
    - development

trigger: none

# Opt out of pull request validation
pr: none

# By default, use self-hosted agents
pool: Default

resources:
  repositories:
    # Azure DevOps repository
    - repository: helsinki-maptiles-pipelines
      type: git
      # Azure DevOps project/repository
      name: helsinki-maptiles/helsinki-maptiles-pipelines

extends:
  # Filename in Azure DevOps Repository
  template: components/helsinki-maptiles/pipelines/helsinki-maptiles-refresh-mbtiles.yml@helsinki-maptiles-pipelines
  parameters:
    targetEnv: ${{ parameters.targetEnv }}